# Generated by Django 3.2 on 2022-03-14 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zayed_university_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='log',
            old_name='user_answer',
            new_name='event_answer',
        ),
    ]
