# Generated by Django 3.2.12 on 2022-03-31 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zayed_university_app', '0002_rename_user_answer_log_event_answer'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=1000)),
                ('answer', models.TextField(max_length=8000)),
            ],
        ),
        migrations.AddField(
            model_name='log',
            name='intent',
            field=models.CharField(default='', max_length=100),
        ),
    ]
